### ISSUE TITLE
dmenu.dmenu.DmenuCommandError: The provided dmenu command could not be used (['dmenu', '-p', 'Enter anime query: ']): [Errno 20] Not a directory: 'dmenu'

### ISSUE THREAD

**Issue by Dankni95** [Dabbing-Guy/anipy-dmenu#3]
```
Traceback (most recent call last):
  File "/home/daniel/.local/lib/python3.10/site-packages/dmenu/dmenu.py", line 175, in show
    proc = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'dmenu'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/anipy-dmenu", line 139, in <module>
    main()
  File "/usr/local/bin/anipy-dmenu", line 114, in main
    user_query = dmenu.show(items=[], prompt="Enter anime query: ")
  File "/home/daniel/.local/lib/python3.10/site-packages/dmenu/dmenu.py", line 183, in show
    raise DmenuCommandError(args, err)
dmenu.dmenu.DmenuCommandError: The provided dmenu command could not be used (['dmenu', '-p', 'Enter anime query: ']): [Errno 20] Not a directory: 'dmenu'

```

Any idea why im getting this error? I think i installed everything correctly

Looks like dmenu didnt install correctly?

**Comment by VoidAny** [comment]
What happens if you run `dmenu -v` in your terminal?

**Comment by Dankni95** [comment]
Its not installed globally, so i cant run dmenu

Probably why im getting the error

**Comment by VoidAny** [comment]
Yeah, you need to install dmenu from its source to use it. 

I recommend you use [Luke Smith's version](https://github.com/LukeSmithxyz/dmenu) of it. 

To install it:

```sh
git clone https://github.com/LukeSmithxyz/dmenu
cd dmenu
sudo make install
```

If you want to change the fonts or colors it uses, edit the config.h file and then `sudo make clean install` it again.

**Comment by Dankni95** [comment]
Ah i thought it got installed through pip or arch dependencies.

Everything works now :+1:  sorry i got confused

**Comment by VoidAny** [comment]
I think that I will update the readme to be more clear about needing to install dmenu.
